### ISSUE TITLE
Hello if I may

### ISSUE THREAD

**Issue by cucurbita** [duaraghav8/Hackerrank-Problems#1]
if I may, I would have gone this way (1); a comment about your coding in general, try learning to delegate splitting into small tasks, identifying your needs before implementing ; use sub-functions ; iteration facilities ; built-in data structures that the language offers you, whatsoever the language, indeed there are million ways to write the same code, but usually there are only two or three (meaning few) which are good ; seek them, style matters as much as performance concerns ; this is a "one package" ; a "working solution" is not a coding solution neither the right answer, this is only 10% of the job, hello world!

1- e.g modulus are your friends.

```python
table_en =
{
	 0: 'Zero',
	 1: 'One',
	 2: 'Two',
	 3: 'Three',
	 4: 'Four',
	 5: 'Five',
     6: 'Six',
     7: 'Seven',
     8: 'Eight',
     9: 'Nine',
    10: 'Ten',
    11: 'Eleven',
    12: 'Twelve',
    13: 'Thirteen',
    14: 'Fourteen',
    15: 'Fifteen',
    16: 'Sixteen',
    17: 'Seventeen',
    18: 'Eighteen',
    19: 'Nineteen',
    20: 'Twenty',
    30: 'Thirty',
    40: 'Forty',
    50: 'Fifty' # last time I checked 8-) 59 is max for minutes
}

table_en_special =
{
	30 : 'Half',
	15 : 'Quarter'
}

def get_time_sentence(hour, mins):
# here let say mins is > 59 then it needs to be translated back to hour:mins 
```

Best.

**Comment by duaraghav8** [comment]
Hey!
I appreciate your feedback, and I see why the code doesn't meet the standards. I'll re-design the program  as soon as I get time.
As for the minutes, I just confirmed with my sources and YES! It is indeed 59 minutes max. But the logic I applied relies on this simple idea:

If minutes = 30 / 45 / 15:
 "Half past ..." / "Quarter to ..." / "Quarter past ..."

If minutes < 30: (for example 29)
 "Twenty Nine minutes PAST ..."

If minutes > 30: (for example 31)
 "Twenty Nine minutes TO ..."

So as far as the problem's needs go, you'll never need to write a number greater than 29 in words.

**Comment by cucurbita** [comment]
Hello,

yes I understand, that's just a long-time ago, I wrote a kind of date formatting query language where I was storing words and masks according to the real language/locale (there isn't really any common rules regarding this) ; then querying by key index the pieces ; thus you just had to swap tables without changing anything to the main parser's logic.

Best.
